"""Statistical validation of backtest results — overfitting defenses.

A backtest that looks good can still be luck. This module quantifies that:

- Permutation tests: break the pairing between signal scores and forward
  returns to build a null distribution of the information coefficient (or
  hit rate) under "signal has no information", and report where the
  observed value sits (p-value). Uses the (count + 1) / (n + 1) estimator
  so p is never exactly zero.

  IMPORTANT: when forward-return windows overlap (horizon > sampling step,
  the usual case), consecutive observations share most of their return
  window and are strongly autocorrelated — they are NOT exchangeable, and
  naive IID shuffling badly overstates significance (verified empirically:
  on no-signal synthetic data it "finds" significant ICs on half the
  names). The IC test therefore uses a circular-rotation null by default:
  each trial rotates the return series by a random offset, preserving its
  autocorrelation structure while destroying any alignment with the
  scores. Set ``method="shuffle"`` only when observations are genuinely
  independent (e.g. non-overlapping windows).
- Random-entry Monte Carlo: compare the strategy's total return against
  random position sequences generated by circularly shifting the actual
  position series — this preserves both the fraction of time in market and
  the run-length structure of positions, isolating *timing skill* from
  *exposure*.
- Block bootstrap: resample daily strategy returns in contiguous blocks
  (preserving short-range autocorrelation) to put a confidence interval
  around the Sharpe ratio instead of trusting a single point estimate.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

TRADING_DAYS_PER_YEAR = 252


@dataclass(frozen=True)
class PermutationTestResult:
    metric: str
    observed: float
    null_mean: float
    null_std: float
    p_value: float
    n_permutations: int

    @property
    def significant(self) -> bool:
        return self.p_value < 0.05


@dataclass(frozen=True)
class MonteCarloResult:
    metric: str
    observed: float
    percentile: float  # 0-100: share of null trials the observed value beats
    null_mean: float
    null_p5: float
    null_p95: float
    n_trials: int


@dataclass(frozen=True)
class BootstrapCI:
    metric: str
    observed: float
    p5: float
    p50: float
    p95: float
    n_trials: int


def _rank_ic(scores: pd.Series, forward_returns: pd.Series) -> float:
    """Spearman information coefficient via pandas ranks (no scipy)."""
    return float(scores.rank().corr(forward_returns.rank()))


def permutation_test_ic(
    scores: pd.Series,
    forward_returns: pd.Series,
    n_permutations: int = 1000,
    seed: int = 0,
    method: str = "rotate",
) -> PermutationTestResult | None:
    """Two-sided permutation test of the Spearman IC.

    ``method="rotate"`` (default) builds the null by circularly rotating
    the return series — the right null when forward-return windows overlap
    and observations are autocorrelated. ``method="shuffle"`` is the
    classic IID permutation, valid only for non-overlapping windows.
    """
    aligned = pd.concat([scores.rename("s"), forward_returns.rename("r")], axis=1).dropna()
    if len(aligned) < 10:
        return None
    s, r = aligned["s"], aligned["r"]
    observed = _rank_ic(s, r)
    if pd.isna(observed):
        return None

    rng = np.random.default_rng(seed)
    r_ranks = r.rank().to_numpy()
    s_ranks = s.rank().to_numpy()
    n = len(r_ranks)
    null = np.empty(n_permutations)
    if method == "rotate":
        # Rotations keep the return series' serial structure intact; with n
        # observations there are only n-1 distinct non-identity offsets, so
        # sample offsets uniformly from [1, n-1].
        offsets = rng.integers(1, n, size=n_permutations)
        for i, k in enumerate(offsets):
            null[i] = np.corrcoef(s_ranks, np.roll(r_ranks, int(k)))[0, 1]
    elif method == "shuffle":
        for i in range(n_permutations):
            null[i] = np.corrcoef(s_ranks, rng.permutation(r_ranks))[0, 1]
    else:
        raise ValueError(f"Unknown method: {method!r} (use 'rotate' or 'shuffle')")
    p_value = (np.sum(np.abs(null) >= abs(observed)) + 1) / (n_permutations + 1)
    return PermutationTestResult(
        metric="Spearman IC",
        observed=observed,
        null_mean=float(null.mean()),
        null_std=float(null.std()),
        p_value=float(p_value),
        n_permutations=n_permutations,
    )


def permutation_test_hit_rate(
    scores: pd.Series,
    forward_returns: pd.Series,
    threshold: float = 60.0,
    n_permutations: int = 1000,
    seed: int = 0,
) -> PermutationTestResult | None:
    """One-sided permutation test of the bullish hit rate.

    Null: the score's timing of bullish calls is uninformative — rotating
    the return series (which preserves its serial structure) should produce
    hit rates just as good. One-sided because only "better than chance
    timing" is the claim being tested.
    """
    aligned = pd.concat([scores.rename("s"), forward_returns.rename("r")], axis=1).dropna()
    mask = (aligned["s"] >= threshold).to_numpy()
    n_bullish = int(mask.sum())
    if n_bullish < 5 or len(aligned) < 10:
        return None
    r_values = aligned["r"].to_numpy()
    observed = float((r_values[mask] > 0).mean())

    rng = np.random.default_rng(seed)
    offsets = rng.integers(1, len(r_values), size=n_permutations)
    null = np.empty(n_permutations)
    for i, k in enumerate(offsets):
        null[i] = (np.roll(r_values, int(k))[mask] > 0).mean()
    p_value = (np.sum(null >= observed) + 1) / (n_permutations + 1)
    return PermutationTestResult(
        metric=f"Hit rate (score >= {threshold:g})",
        observed=observed,
        null_mean=float(null.mean()),
        null_std=float(null.std()),
        p_value=float(p_value),
        n_permutations=n_permutations,
    )


def monte_carlo_random_entry(
    daily_returns: pd.Series,
    position: pd.Series,
    n_trials: int = 1000,
    seed: int = 0,
) -> MonteCarloResult | None:
    """Compare strategy timing against circularly-shifted position sequences.

    Each trial rolls the actual 0/1 position series by a random offset, so
    every null strategy has the exact same time-in-market and run-length
    structure — only the *timing* is destroyed. If the real strategy's
    total return doesn't clearly beat this null, the signal adds no timing
    information beyond its market exposure.
    """
    aligned = pd.concat(
        [daily_returns.rename("ret"), position.rename("pos")], axis=1
    ).dropna()
    if len(aligned) < 60 or aligned["pos"].sum() == 0:
        return None
    rets = aligned["ret"].to_numpy()
    pos = aligned["pos"].to_numpy()
    observed = float(np.prod(1 + rets * pos) - 1)

    rng = np.random.default_rng(seed)
    offsets = rng.integers(1, len(pos) - 1, size=n_trials)
    null = np.empty(n_trials)
    for i, k in enumerate(offsets):
        null[i] = np.prod(1 + rets * np.roll(pos, int(k))) - 1
    percentile = float((null < observed).mean() * 100)
    return MonteCarloResult(
        metric="Total return vs random-timing null",
        observed=observed,
        percentile=percentile,
        null_mean=float(null.mean()),
        null_p5=float(np.percentile(null, 5)),
        null_p95=float(np.percentile(null, 95)),
        n_trials=n_trials,
    )


def _annualized_sharpe(daily: np.ndarray) -> float | None:
    std = daily.std(ddof=1)
    if std == 0 or np.isnan(std):
        return None
    return float(daily.mean() / std * np.sqrt(TRADING_DAYS_PER_YEAR))


def block_bootstrap_sharpe(
    strategy_daily_returns: pd.Series,
    block_size: int = 10,
    n_trials: int = 1000,
    seed: int = 0,
) -> BootstrapCI | None:
    """Moving-block bootstrap CI for the annualized Sharpe ratio."""
    daily = strategy_daily_returns.dropna().to_numpy()
    if len(daily) < block_size * 4:
        return None
    observed = _annualized_sharpe(daily)
    if observed is None:
        return None

    rng = np.random.default_rng(seed)
    n_blocks = int(np.ceil(len(daily) / block_size))
    max_start = len(daily) - block_size
    sharpes = []
    for _ in range(n_trials):
        starts = rng.integers(0, max_start + 1, size=n_blocks)
        sample = np.concatenate([daily[s : s + block_size] for s in starts])[: len(daily)]
        sharpe = _annualized_sharpe(sample)
        if sharpe is not None:
            sharpes.append(sharpe)
    if len(sharpes) < n_trials // 2:
        return None
    arr = np.array(sharpes)
    return BootstrapCI(
        metric="Annualized Sharpe",
        observed=observed,
        p5=float(np.percentile(arr, 5)),
        p50=float(np.percentile(arr, 50)),
        p95=float(np.percentile(arr, 95)),
        n_trials=len(sharpes),
    )
